services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: productuser
      POSTGRES_PASSWORD: productpass
      POSTGRES_DB: products
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U productuser -d products"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: productuser
      DB_PASSWORD: productpass
      DB_NAME: products
      CACHE_SIZE: "10000"
    depends_on:
      postgres:
        condition: service_healthy
    command: ["./wait-for.sh", "postgres:5432", "--", "./product-api"]

volumes:
  pgdata: